jwt:
  secret: 1CE6EB6421E1BD88C4E144CCE1491
  expire-milli-seconds: 600000
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 517523270174-33pcdbb2cuo7s1ve9ri86aaehvobsu4m.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8000/login/oauth2/code/google
            scope:
              - email
              - profile