server:
  port: 8000
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 517523270174-vm32dl4itm2hc398qkn3mgluoqbfmf8f.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile